services:
  - type: web
    name: job-assistant
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12  # Changé de 3.11 à 3.12
